apiVersion: v1
kind: Service
metadata:
  name: healthandmed-api-service
spec:
  selector:
    app: healthandmed-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      nodePort: 31023
  type: NodePort
