name: CI Pipeline

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
  deploy:
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'  # opcional: só executar deploy no master

    steps:
      - uses: actions/checkout@v4
      
      # Configurar o Docker (pode não ser necessário se o runner já tem Docker instalado)
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Fazer login no Docker Hub usando secrets armazenados no repositório
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: username
          password: password

      # Construir a imagem Docker
      - name: Build Docker image
        run: |
          docker build -f HealthAndMed.API/Dockerfile -t guisatech/healthandmed:latest .

      # Publicar a imagem Docker no Docker Hub
      - name: Push Docker image
        run: |
          docker push guisatech/healthandmed:latest
